site_name: LancerA's Blog
site_description: 一个有啥说啥的神奇网站
site_url: https://codelancera-offical.github.io/My-Blog


theme:
  name: material
  features:
    - navigation.indexes # 自定义导航页

plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Workflow
        - Life
  - tags

nav:
  - Home: index.md
  - Blog: blog/index.md
  - Workflow: workflow/index.md

docs_dir: docs         # Markdown 和资源文件的目录
site_dir: site         # 静态网站生成目录